### PR TITLE
Use Github Actions to build GNURadio cross platform

### PR DESCRIPTION
**Pull request by robbiet480**
Continuing follow up from https://github.com/robotastic/trunk-recorder/issues/365. Let's merge after #3. This is the same config as https://github.com/robotastic/trunk-recorder/pull/371, meaning you'll need to add the secrets to this repo as well.

### CODE REVIEW

**Comment by robbiet480** [comment]
@robotastic Mind merging this too?

**Comment by robotastic** [comment]
OK! Secrets update - let's merge this and see what happens!

**Comment by robotastic** [comment]
Interesting - it doesn't look like there is a Ubuntu 20.04 image for ARM v6:
https://hub.docker.com/_/ubuntu?tab=tags

**Comment by robbiet480** [comment]
Checking. Also, I'm on trunk-recorder Gitter if you want to chat about this.

**Pull request merged**
