### PR TITLE
Removing ffmpeg installation and replacing with fdkaac, sox

### PR DESCRIPTION
**Pull request by EricTendian**
With the recent changes to trunk-recorder, `ffmpeg` was replaced with `fdkaac`. As such, there isn't a need to compile ffmpeg anymore. Additionally, `fdkaac` and `sox` needs to be installed for the uploading to OpenMHz to work.

This PR cleans up the Dockerfile to include only what's needed for running trunk-recorder, so it should speed up the process.

Also, I noticed Ubuntu 16.04 was being used, and with Ubuntu 20.04 around the corner, it seemed reasonable to update to the current LTS release for more security updates. The difference in gnuradio versions is 3.7.9 vs 3.7.11, so didn't seem like it would introduce any breaking changes.

I tested these changes by compiling a new trunk-recorder Docker image and I was successful, audio uploads are still working (see https://openmhz.com/system/chi_cpd).

### CODE REVIEW

**Comment by EricTendian** [comment]
I added a few more packages based on new cmake package dependencies to be introduced.

**Comment by robotastic** [comment]
I forgot about this repo! Whoops...

**Comment by EricTendian** [comment]
@robotastic thanks for merging! If you don't mind, could you turn on automatic builds for the Docker Hub repository https://hub.docker.com/r/robotastic/docker-gnuradio? Looks like the Docker image there hasn't been rebuilt.

I was also thinking perhaps this Dockerfile could just become part of the trunk-recorder Dockerfile, so in case any dependency changes are made later it can all be done in one repo.

**Comment by robotastic** [comment]
I thought I had turned that on… let me go kick it and re-set that up.

**Comment by robotastic** [comment]
Just kicked off a build in Docker Hub. Also relinked my account so auto builds should also be working again.

**Comment by EricTendian** [comment]
@robotastic thanks! Do you mind also setting that up for the trunk-recorder repo? Looks like that image is quite out-of-date too.

**Comment by robotastic** [comment]
I thought I did and I manually kicked off a build. Let me see if it failed or something.

**Comment by EricTendian** [comment]
@robotastic just wanted to check to see if you had a chance to look into this? Not seeing anything in the builds tab on Docker Hub. No rush if there's stuff that needs to be fixed for it to be automatic.

**Comment by robotastic** [comment]
Let me go look into things. looks like the build failed.
````
-- Found UHD: /usr/lib/x86_64-linux-gnu/libuhd.so
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g")
-- Configuring incomplete, errors occurred!
See also "/src/trunk-recorder/CMakeFiles/CMakeOutput.log".
[91mCMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR)
Call Stack (most recent call first):
/usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
/usr/share/cmake-3.5/Modules/FindCURL.cmake:61 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
CMakeLists.txt:106 (find_package)
[0m
Removing intermediate container 05d85d0eab74
The command '/bin/sh -c cd /src/trunk-recorder && cmake . && make' returned a non-zero code: 1
````

**Comment by robotastic** [comment]
I am trying a rebuild now... it may have been that the underlying container with CURL hadn't finished building yet. It might make sense to also build out a branch of this so we can have some pre-built GR3.8 Docker Containers.

**Comment by EricTendian** [comment]
@robotastic thanks! It looks like that worked.

**Pull request merged**
